# Generated by Django 3.0.7 on 2020-06-11 03:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.TextField()),
                ('last_name', models.TextField()),
                ('email', models.TextField()),
                ('portfolio', models.TextField()),
                ('current_location', models.TextField()),
                ('birthday', models.TextField()),
                ('high_school', models.TextField()),
                ('college', models.TextField()),
                ('role', models.TextField()),
                ('online', models.TextField()),
                ('gender', models.TextField()),
                ('username', models.TextField()),
                ('password', models.TextField()),
            ],
        ),
    ]
